attribute-author: false
attribute-committer: false
auto-lint: false
check-update: false
gitignore: false
subtree-only: true
watch-files: true

model: "openrouter/anthropic/claude-sonnet-4"
weak-model: "openrouter/google/gemini-2.0-flash-001"
