[character]
success_symbol = "[%](bold green)"
error_symbol = "[%](bold red)"

[time]
disabled = false

[hostname]
ssh_only = false

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
